services:
  mco-drought:
    user: "rstudio"
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: mco-drought-pipeline:latest
    container_name: mco-drought
    environment:
      TZ: America/Denver
      CORES: "8"
      KEEP_TILES: "0"
      CONUS_MASK: "1"
      TILE_DX: "2"
      TILE_DY: "2"
      CLIM_PERIODS: "rolling:30,full"
      # Examples:
      # CLIM_PERIODS: "rolling:30,fixed:1991:2020"
      # CLIM_PERIODS: "fixed:1991:2020,full"
    mem_limit: 30g
    mem_reservation: 8g
    volumes:
      - ${HOME}/mco-drought-conus:/home/rstudio/mco-drought-conus:rw
      - ${HOME}/mco-drought-conus-data:/home/rstudio/mco-drought-conus-data:rw
    restart: "no"
